# syntax=docker/dockerfile:1
FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download
COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux go build -p 1 -o main .


FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/main .

RUN apk --no-cache add tzdata
EXPOSE 8080
CMD ["./main"]